static LRESULT __stdcall OrderComboWndProc(HWND h,UINT msg,WPARAM w,LPARAM l){if(msg==WM_MOUSEWHEEL&&!SendMessageW(h,CB_GETDROPPEDSTATE,0,0)){short delta=(short)((w>>16)&0xFFFF);int idx=(int)SendMessageW(h,CB_GETCURSEL,0,0);int count=(int)SendMessageW(h,0x0146,0,0);int step=delta>0?-1:1;int next=idx+step;if(next<0)next=0;if(next>=count)next=count-1;if(next!=idx){SendMessageW(h,CB_SETCURSEL,(WPARAM)next,0);selectOrder(orderFromComboIndex(next));}return 0;}return gOrderComboOldProc?CallWindowProcW(gOrderComboOldProc,h,msg,w,l):DefWindowProcW(h,msg,w,l);}
static void installOrderComboWheel(){COMBOBOXINFO ci;memset(&ci,0,sizeof(ci));ci.cbSize=(DWORD)sizeof(ci);gOrderComboOldProc=(WNDPROC)(LONG_PTR)SetWindowLongPtrW(gOrderCombo,GWL_WNDPROC,(LONG_PTR)OrderComboWndProc);if(GetComboBoxInfo(gOrderCombo,&ci)&&ci.hwndList){gOrderListWnd=ci.hwndList;gOrderListOldProc=(WNDPROC)(LONG_PTR)SetWindowLongPtrW(gOrderListWnd,GWL_WNDPROC,(LONG_PTR)OrderListWndProc);}}

static LRESULT __stdcall RenderWndProc(HWND h,UINT msg,WPARAM w,LPARAM l){if(msg==WM_SIZE){gWidth=(int)(l&0xFFFF);gHeight=(int)((l>>16)&0xFFFF);return 0;}if(msg==WM_KEYDOWN){handleShortcut((UINT)w);return 0;}if(msg==WM_LBUTTONDOWN){gDragging=TRUE;gLastX=(short)(l&0xFFFF);gLastY=(short)((l>>16)&0xFFFF);SetCapture(h);return 0;}if(msg==WM_LBUTTONUP){gDragging=FALSE;ReleaseCapture();return 0;}if(msg==WM_MOUSEMOVE&&gDragging){int x=(short)(l&0xFFFF),y=(short)((l>>16)&0xFFFF);gYaw+=(float)(x-gLastX)*0.38f;gPitch+=(float)(y-gLastY)*0.38f;while(gYaw>360.0f)gYaw-=360.0f;while(gYaw<-360.0f)gYaw+=360.0f;while(gPitch>360.0f)gPitch-=360.0f;while(gPitch<-360.0f)gPitch+=360.0f;gLastX=x;gLastY=y;return 0;}if(msg==WM_MOUSEWHEEL){short delta=(short)((w>>16)&0xFFFF);gZoom+=(delta>0)?0.65f:-0.65f;gZoom=fclamp(gZoom,-32.0f,-4.2f);return 0;}return DefWindowProcW(h,msg,w,l);}
static LRESULT __stdcall WndProc(HWND h,UINT msg,WPARAM w,LPARAM l){if(msg==WM_DESTROY){gAbortRequested=TRUE;PostQuitMessage(0);return 0;}if(msg==WM_SIZE){int cw=(int)(l&0xFFFF),ch=(int)((l>>16)&0xFFFF),top=144,rh=ch-top;if(rh<1)rh=1;if(gRenderWnd)MoveWindow(gRenderWnd,0,top,cw,rh,TRUE);if(gPaperText){int px=cw-548;if(px<18)px=18;MoveWindow(gPaperText,px,top+18,520,132,TRUE);}return 0;}if(msg==WM_COMMAND){int id=(int)(w&0xFFFF),notify=(int)((w>>16)&0xFFFF);if(id==1200&&notify==(int)CBN_SELCHANGE){int idx=(int)SendMessageW(gOrderCombo,CB_GETCURSEL,0,0);selectOrder(orderFromComboIndex(idx));}else if(id==1250&&notify==(int)CBN_SELCHANGE){int mode=(int)SendMessageW(gPlaybackModeCombo,CB_GETCURSEL,0,0);if(mode==1)SetWindowTextW(gPlaybackValueEdit,L"30");else if(mode==2)SetWindowTextW(gPlaybackValueEdit,L"1.0");setButtons();updateStatus();}else if(id==1301)doScramble();else if(id==1302)doSolve();else if(id==1303)doReset();else if(id==1304)doPlay();return 0;}if(msg==WM_KEYDOWN){handleShortcut((UINT)w);return 0;}return DefWindowProcW(h,msg,w,l);}
static HWND makeCtrl(const wchar_t* cls,const wchar_t* text,DWORD style,int x,int y,int w,int h,int id){return CreateWindowExW(0,cls,text,WS_CHILD|WS_VISIBLE|style,x,y,w,h,gWnd,(HMENU)(UINT_PTR)id,gInst,0);}
static void addCombo(HWND h,const wchar_t* s){SendMessageW(h,CB_ADDSTRING,0,(LPARAM)s);}

extern "C" void WinMainCRTStartup(){SetProcessDPIAware();LARGE_INTEGER fq;QueryPerformanceFrequency(&fq);gInvFreq=1.0/(double)fq.QuadPart;gInst=GetModuleHandleW(0);HICON appIcon=LoadIconW(gInst,(LPCWSTR)(UINT_PTR)101);if(!appIcon)appIcon=LoadIconW(0,(LPCWSTR)(UINT_PTR)32512);WNDCLASSW wc;memset(&wc,0,sizeof(wc));wc.lpfnWndProc=WndProc;wc.hInstance=gInst;wc.hCursor=LoadCursorW(0,(LPCWSTR)(UINT_PTR)32512);wc.hIcon=appIcon;wc.hbrBackground=(HBRUSH)(UINT_PTR)6;wc.lpszClassName=L"TensorCubeWindow";if(!RegisterClassW(&wc))ExitProcess(1);WNDCLASSW rc;memset(&rc,0,sizeof(rc));rc.style=CS_OWNDC;rc.lpfnWndProc=RenderWndProc;rc.hInstance=gInst;rc.hCursor=LoadCursorW(0,(LPCWSTR)(UINT_PTR)32512);rc.lpszClassName=L"TensorCubeRender";if(!RegisterClassW(&rc))ExitProcess(1);gWnd=CreateWindowExW(0,L"TensorCubeWindow",L"TensorCube - GPU Tensor Iteration Solver",WS_OVERLAPPEDWINDOW|WS_VISIBLE,CW_USEDEFAULT,CW_USEDEFAULT,1500,930,0,0,gInst,0);if(!gWnd)ExitProcess(2);RECT cr;GetClientRect(gWnd,&cr);int cw=cr.right-cr.left,ch=cr.bottom-cr.top,top=144,rh=ch-top;if(rh<1)rh=1;gRenderWnd=CreateWindowExW(0,L"TensorCubeRender",L"",WS_CHILD|WS_VISIBLE,0,top,cw,rh,gWnd,0,gInst,0);if(!gRenderWnd)ExitProcess(2);gDC=GetDC(gRenderWnd);PIXELFORMATDESCRIPTOR pfd;memset(&pfd,0,sizeof(pfd));pfd.nSize=sizeof(pfd);pfd.nVersion=1;pfd.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL|PFD_DOUBLEBUFFER;pfd.iPixelType=PFD_TYPE_RGBA;pfd.cColorBits=32;pfd.cDepthBits=24;pfd.cStencilBits=8;pfd.iLayerType=PFD_MAIN_PLANE;int pf=ChoosePixelFormat(gDC,&pfd);if(!pf||!SetPixelFormat(gDC,pf,&pfd))ExitProcess(3);gGL=createBestCompatibilityContext(gDC);if(!gGL)ExitProcess(4);glEnable(GL_DEPTH_TEST);gComputeReady=initComputePipeline();if(gComputeReady)initHighMatrixFreeRenderer();initTensorCore();if(!initCpuWorkerPool()){MessageBoxW(gWnd,L"CPU resource-return worker pool initialization failed",L"TensorCube",MB_OK|MB_ICONERROR);ExitProcess(5);}

    makeCtrl(L"STATIC",L"阶数",SS_LEFT,16,12,42,22,1100);
    gOrderCombo=makeCtrl(L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP|WS_VSCROLL,58,8,178,620,1200);
    for(int n=2;n<=49;n++){wchar_t lab[32];wchar_t* p=lab;*p=0;p=wappendInt(p,n);p=wappend(p,L"阶");addCombo(gOrderCombo,lab);}
    addCombo(gOrderCombo,L"100阶");addCombo(gOrderCombo,L"1000阶");addCombo(gOrderCombo,L"10000阶");addCombo(gOrderCombo,L"100000阶");
    SendMessageW(gOrderCombo,CB_SETCURSEL,1,0);installOrderComboWheel();

    gBtnScramble=makeCtrl(L"BUTTON",L"深随机",BS_PUSHBUTTON|WS_TABSTOP,248,8,92,30,1301);
    gBtnSolve=makeCtrl(L"BUTTON",L"求解",BS_PUSHBUTTON|WS_TABSTOP,348,8,82,30,1302);
    gBtnPlay=makeCtrl(L"BUTTON",L"播放",BS_PUSHBUTTON|WS_TABSTOP,438,8,82,30,1304);
    gBtnReset=makeCtrl(L"BUTTON",L"复位",BS_PUSHBUTTON|WS_TABSTOP,528,8,70,30,1303);

    makeCtrl(L"STATIC",L"播放速度",SS_LEFT,624,12,64,22,1110);
    gPlaybackModeCombo=makeCtrl(L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP,692,8,156,200,1250);
    addCombo(gPlaybackModeCombo,L"默认");addCombo(gPlaybackModeCombo,L"目标总耗时");addCombo(gPlaybackModeCombo,L"相对倍速");
    SendMessageW(gPlaybackModeCombo,CB_SETCURSEL,0,0);
    gPlaybackValueEdit=makeCtrl(L"EDIT",L"1.0",ES_AUTOHSCROLL|WS_TABSTOP,856,8,82,30,1251);
    makeCtrl(L"STATIC",L"总耗时填秒数；倍速 2.0 = 2×",SS_LEFT,948,12,260,22,1111);

    gStatus=makeCtrl(L"STATIC",L"",SS_LEFT,16,48,1460,20,1400);
    gGpuText=makeCtrl(L"STATIC",L"",SS_LEFT,16,72,1460,20,1401);
    gSolverText=makeCtrl(L"STATIC",L"",SS_LEFT,16,96,1460,20,1402);
    gHint=makeCtrl(L"STATIC",L"拖动环绕 · 滚轮缩放（近距自动虚化） · S 深随机 · R 求解 · P 播放",SS_LEFT,16,120,800,20,1403);
    {int px=cw-548;if(px<18)px=18;gPaperText=makeCtrl(L"STATIC",L"",SS_LEFT,px,top+18,520,132,1410);}

    if(!initOrder(3)){MessageBoxW(gWnd,L"initial order allocation failed",L"TensorCube",MB_OK|MB_ICONERROR);ExitProcess(5);}setButtons();updateStatus();updateGpuText();ShowWindow(gWnd,SW_SHOW);UpdateWindow(gWnd);MSG m;BOOL running=TRUE;while(running){while(PeekMessageW(&m,0,0,0,PM_REMOVE)){if(m.message==0x0012){running=FALSE;break;}TranslateMessage(&m);DispatchMessageW(&m);}if(!running)break;if(gSolveUiState==TC_FACTORIZING)mfAdvanceExactFactorCurrentTensor();
        updateAnimation();render();Sleep(1);}gAbortRequested=TRUE;gpuDrainForShutdown();shutdownCpuWorkerPool();shutdownTensorCore();freeOrderMemory();wglMakeCurrent(0,0);if(gGL)wglDeleteContext(gGL);if(gDC)ReleaseDC(gRenderWnd,gDC);ExitProcess(0);}
