    *tokens=*records=*bad=0;pglBindBuffer(GL_SHADER_STORAGE_BUFFER,s->resultBuf);
    unsigned int* q=(unsigned int*)pglMapBuffer(GL_SHADER_STORAGE_BUFFER,GL_READ_ONLY);if(!q)return FALSE;
    BOOL tc=FALSE;if(gTensorCoreReady&&gTensorCoreReductionActive)tc=tensorCoreReduceGpuResults(q,s->groups,tokens,records,bad);
    if(!tc)for(unsigned int i=0;i<s->groups;i++){*tokens+=(unsigned long long)q[i*3u];*records+=(unsigned long long)q[i*3u+1u];*bad+=(unsigned long long)q[i*3u+2u];}
    pglUnmapBuffer(GL_SHADER_STORAGE_BUFFER);return TRUE;
}
static BOOL gpuCollectSlot(GpuSlot* s,BOOL updateStats){if(!s->busy)return TRUE;unsigned int st=pglClientWaitSync(s->fence,0,0);if(st==GL_TIMEOUT_EXPIRED)return TRUE;if(st==GL_WAIT_FAILED){tcAtomicExchange(&gWorkFailed,1);return FALSE;}if(st!=GL_ALREADY_SIGNALED&&st!=GL_CONDITION_SATISFIED)return TRUE;unsigned long long tok=0,rec=0,bad=0;if(!gpuReadSlotResult(s,&tok,&rec,&bad)){tcAtomicExchange(&gWorkFailed,1);return FALSE;}double dt=nowSeconds()-s->submitTime;if(updateStats){tcAtomicExchangeAdd64(&gWorkCompleted,(LONGLONG)s->count);tcAtomicExchangeAdd64(&gWorkRecords,(LONGLONG)rec);tcAtomicExchangeAdd64(&gWorkTokens,(LONGLONG)tok);gGpuCompleted+=(unsigned long long)s->count;gGpuRecords+=rec;gGpuTokens+=tok;gGpuBusySeconds+=dt;if(bad){gExactPlanPass=FALSE;tcAtomicExchange(&gWorkFailed,1);}if(dt<0.040&&gGpuBatchComponents<TC_GPU_BATCH_MAX){unsigned int n=gGpuBatchComponents<<1;gGpuBatchComponents=n>TC_GPU_BATCH_MAX?TC_GPU_BATCH_MAX:n;}else if(dt>0.250&&gGpuBatchComponents>TC_GPU_BATCH_MIN){unsigned int n=gGpuBatchComponents>>1;gGpuBatchComponents=n<TC_GPU_BATCH_MIN?TC_GPU_BATCH_MIN:n;}}
    pglDeleteSync(s->fence);s->fence=0;s->busy=FALSE;return bad?FALSE:TRUE;}
static int gpuBusySlotCount(){int n=0;for(int i=0;i<TC_GPU_SLOTS;i++)if(gGpuSlots[i].busy)n++;return n;}
static unsigned int gpuChooseClaimSize(){LONGLONG next=gWorkNext;if(next>=gWorkTotal)return 0u;unsigned long long remain=(unsigned long long)(gWorkTotal-next);if(remain<(unsigned long long)TC_GPU_BATCH_MIN*2ull)return 0u;unsigned int want=gGpuBatchComponents;unsigned long long soft=remain/4ull;if(soft<(unsigned long long)want)want=(unsigned int)(soft<(unsigned long long)TC_GPU_BATCH_MIN?TC_GPU_BATCH_MIN:soft);if((unsigned long long)want>remain)want=(unsigned int)remain;return want;}
static void gpuFillReadySlots(){if(!gGpuJobEnabled||gWorkFailed)return;for(int i=0;i<TC_GPU_SLOTS;i++)if(!gGpuSlots[i].busy){unsigned int want=gpuChooseClaimSize();if(!want)break;unsigned long long start=claimReadyWork(want);if(start>=(unsigned long long)gWorkTotal)break;unsigned long long rem=(unsigned long long)gWorkTotal-start;unsigned int count=rem<(unsigned long long)want?(unsigned int)rem:want;if(start>0xffffffffull||start+(unsigned long long)count>0x100000000ull){tcAtomicExchange(&gWorkFailed,1);break;}if(!gpuDispatchSlot(&gGpuSlots[i],(unsigned int)start,count)){tcAtomicExchange(&gWorkFailed,1);break;}}}
static void gpuPollAndRefill(){if(!gGpuJobEnabled)return;for(int i=0;i<TC_GPU_SLOTS;i++)gpuCollectSlot(&gGpuSlots[i],TRUE);gpuFillReadySlots();}
static void gpuDrainForShutdown(){for(int i=0;i<TC_GPU_SLOTS;i++){GpuSlot* s=&gGpuSlots[i];if(!s->busy)continue;if(s->fence){for(int spin=0;spin<2000;spin++){unsigned int st=pglClientWaitSync(s->fence,0,1000000ull);if(st==GL_ALREADY_SIGNALED||st==GL_CONDITION_SATISFIED||st==GL_WAIT_FAILED)break;}pglDeleteSync(s->fence);s->fence=0;}s->busy=FALSE;}gGpuJobEnabled=FALSE;}

static BOOL gpuCrossCheck(){if(!gComputeReady||gMfComponentCount==0||gMfComponentCount>0xffffffffull)return FALSE;unsigned int count=(unsigned int)(gMfComponentCount<512ull?gMfComponentCount:512ull);GpuSlot* s=&gGpuSlots[0];if(s->busy)return FALSE;if(!gpuDispatchSlot(s,0u,count))return FALSE;for(;;){unsigned int st=pglClientWaitSync(s->fence,0,1000000ull);if(st==GL_ALREADY_SIGNALED||st==GL_CONDITION_SATISFIED)break;if(st==GL_WAIT_FAILED)return FALSE;pumpUi();if(gAbortRequested)return FALSE;}unsigned long long gt=0,gr=0,gb=0;if(!gpuReadSlotResult(s,&gt,&gr,&gb))return FALSE;pglDeleteSync(s->fence);s->fence=0;s->busy=FALSE;unsigned long long ct=0,cr=0;MfCursor cur;if(!mfCursorSeek(&cur,0))return FALSE;for(unsigned int i=0;i<count;i++){BigComponent c;unsigned long long ci;if(!mfCursorNext(&cur,&c,&ci))return FALSE;CompactFactor f;BOOL nonId=FALSE;SPerm id;if(!mfFactorOne(ci,c,&f,&nonId,&id))return FALSE;if(nonId){cr++;ct+=(unsigned long long)f.tokenCount;}}if(gb||gt!=ct||gr!=cr)return FALSE;return TRUE;}

static BOOL mfStartQuotientPhase(){
    mfReleasePlan();gMfQuotientClassCount=(gOrder+1)/2;gMfQuotientClassBits=(BYTE*)valloc((unsigned long long)gMfQuotientClassCount);if(!gMfQuotientClassBits)return FALSE;memset(gMfQuotientClassBits,0,(unsigned long long)gMfQuotientClassCount);
    gWorkTotal=(LONGLONG)gMfQuotientClassCount;tcAtomicExchange64(&gWorkNext,0);tcAtomicExchange64(&gWorkCompleted,0);tcAtomicExchange(&gWorkFailed,0);resetWorkerStats();wakeCpuWorkers(WK_QUOTIENT);gFactorStage=1;return TRUE;
}
static void resetFactorWorkCounters(){tcAtomicExchange64(&gWorkNext,0);tcAtomicExchange64(&gWorkCompleted,0);tcAtomicExchangeAdd64(&gCpuCompleted,-gCpuCompleted);tcAtomicExchangeAdd64(&gWorkRecords,-gWorkRecords);tcAtomicExchangeAdd64(&gWorkTokens,-gWorkTokens);tcAtomicExchange(&gWorkFailed,0);gGpuCompleted=gGpuRecords=gGpuTokens=0;gGpuBusySeconds=0.0;gGpuBatchComponents=TC_GPU_BATCH_START;gMfProgress=0;gMfFactorRecordCount=0;gMacroTokenCount=0;}
static BOOL mfBeginFactorPhase(){
    if(!buildQuotientPlanFromPublishedBits())return FALSE;gWorkTotal=(LONGLONG)gMfComponentCount;resetFactorWorkCounters();resetWorkerStats();gExactPlanPass=FALSE;gGpuJobEnabled=FALSE;gGpuCrossCheckState=0;
    if(gComputeReady&&gMfComponentCount<=0xffffffffull&&gpuUploadTemplates()){if(gpuCrossCheck()){gGpuJobEnabled=TRUE;gGpuCrossCheckState=1;}else{gGpuCrossCheckState=-1;setDiag(gComputeDiag,2048,L"GPU exact factorizer cross-check failed; work-conserving CPU pool fallback active");}}
    if(gGpuJobEnabled)gpuFillReadySlots();wakeCpuWorkers(WK_FACTOR);gFactorStage=2;return TRUE;
}
static BOOL mfStartExactFactorCurrentTensor(){if(!gMfHasRandom||!gMfDesc.valid||gCpuWorkerCount<=0)return FALSE;gFactorStart=nowSeconds();gFactorElapsedMs=0.0;gLastProgressUi=0.0;gFactorStage=0;gMfProgress=0;gMfFactorRecordCount=0;gMacroTokenCount=0;gPrimitiveCount=0;gExactPlanPass=FALSE;if(!mfPrepareTemplatesForOrder())return FALSE;return mfStartQuotientPhase();}
static void mfFailAsync(const wchar_t* text){gExactPlanPass=FALSE;gSolveUiState=TC_FAILED;wchar_t* p=gSolveFailure;*p=0;p=wappend(p,text);gFactorStage=0;gGpuJobEnabled=FALSE;setButtons();updateStatus();}
static void mfAdvanceExactFactorCurrentTensor(){if(gSolveUiState!=TC_FACTORIZING)return;double now=nowSeconds();gFactorElapsedMs=(now-gFactorStart)*1000.0;if(gAbortRequested){tcAtomicExchange(&gWorkFailed,1);return;}
    if(gFactorStage==1){gMfProgress=(unsigned long long)gWorkCompleted;if(gWorkFailed){mfFailAsync(L"quotient relation reduction failed");return;}if(gCpuWorkersDone>=gCpuWorkerCount){if(!mfBeginFactorPhase()){mfFailAsync(L"published quotient plan or factor phase initialization failed");return;}}}
    else if(gFactorStage==2){if(gGpuJobEnabled)gpuPollAndRefill();gMfProgress=(unsigned long long)gWorkCompleted;gMfFactorRecordCount=(unsigned long long)gWorkRecords;gMacroTokenCount=(unsigned long long)gWorkTokens;if(gWorkFailed){mfFailAsync(L"work-conserving CPU/GPU component factorization failed exact validation");return;}BOOL workersDone=(gCpuWorkersDone>=gCpuWorkerCount)?TRUE:FALSE;BOOL gpuDone=(!gGpuJobEnabled||gpuBusySlotCount()==0)?TRUE:FALSE;if(workersDone&&gpuDone&&gMfProgress>=gMfComponentCount){gMfProgress=gMfComponentCount;gPrimitiveCount=(unsigned long long)gQuotientMoveCount+gMacroTokenCount*10ull;gMfPathReady=TRUE;gExactPlanPass=TRUE;gFactorStage=0;gSolveUiState=TC_PATH_READY;setButtons();updateStatus();return;}}
    if(now-gLastProgressUi>=0.10){gLastProgressUi=now;updateSolverLine();}
}
static void mfPlaybackReset(){mfCursorReset(&gMfPlaybackCursor);gMfPlaybackRecordActive=FALSE;gPlaybackFactorLevel=-1;gPlaybackFactorWordIndex=0;}
static BOOL mfReadNextFactorRecord(StreamFactorRecord* r){BigComponent c;unsigned long long ci;while(mfCursorNext(&gMfPlaybackCursor,&c,&ci)){CompactFactor f;BOOL nonId=FALSE;SPerm id;if(!mfFactorOne(ci,c,&f,&nonId,&id))return FALSE;if(!nonId)continue;r->a=c.a;r->b=c.b;r->chir=c.chir;r->type=c.type;r->size=c.size;r->baseLen=f.baseLen;for(int i=0;i<SG_MAX_BASE;i++)r->chosen[i]=f.chosen[i];r->tokenCount=f.tokenCount;return TRUE;}return FALSE;}
